server:
  port: 8080

spring:
  application:
    name: eduction-web-door8080
  mvc:
    #静态文件请求匹配方式
    static-path-pattern: /**
  resources:
    #修改默认的静态寻址资源目录
    static-locations: classpath:/static/
  messages:
    #国际化
    basename: i18n.common
#  profiles:
#    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aloogn.door.entities #所有entity别名类包

#常用数据
aloogn:
  #白名单
  whiteList: signIn
  basePackage: com.aloogn.door.app.todo



